[COMPUTERWELT]
ring 3 = interface
ring 2 = apps
ring 1 = system
ring 0 = kernel
ring -1 = firmware
ring -2 = SSM_Virt
ring -3 = intel_me
ring -3 = amd_psp

[PHONEWELT]
EL0 = apps
EL1 = systemvirtualize
EL2 = kernel
EL3 = firmware

[RISCV]
U-mode = apps 
S-mode = kernel
M-mode = Machine

[jump_x86]
jump ring3
jump ring2
jump ring1
jump ring0
jump ring -1

[jump_ARM]
jump EL0
jump EL1
jmp EL2

[Jump_riscv]
jump U-mode
jump S-mode